blank_issues_enabled: false
contact_links:
  - name: Documentação do IPIT
    url: https://github.com/smp-sandramariapereira/IPIT-IdeathonPedagogicoInovacaoTecnologica
    about: Consulte os materiais antes de abrir uma dúvida.
